# Generated by Django 4.1.1 on 2023-03-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("retail", "Retail"),
                    ("group", "Group"),
                    ("credit", "Credit"),
                    ("funeral", "Funeral"),
                    ("commuter", "Commuter"),
                ],
                max_length=255,
            ),
        ),
    ]
