# Generated by Django 4.1.1 on 2022-11-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_insuranceproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='policy_document_template',
            field=models.TextField(blank=True),
        ),
    ]
