# Generated by Django 4.1.1 on 2023-06-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FailedUploadData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("member", models.JSONField(default=dict)),
                ("member_type", models.CharField(max_length=255)),
                ("reason", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MemberUploadOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("identification_number", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("product", models.IntegerField()),
                ("reasons", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PricingPlanSchemeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("scheme_type", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TemporaryCancelledMemberData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("main_member_identification_number", models.CharField(max_length=255)),
                ("identification_number", models.CharField(max_length=255)),
                ("identification_method", models.IntegerField()),
                ("product", models.IntegerField()),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TemporaryDataHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            (
                                "dependents_and_beneficiaries",
                                "Beneficiaries & Dependents",
                            ),
                            ("new_members", "New Members"),
                            ("paid_members", "Paid Members"),
                            ("cancelled_members", "Cancelled Members"),
                            ("lapsed_members", "Lapsed Members"),
                        ],
                        max_length=255,
                    ),
                ),
                ("upload_data", models.JSONField(default=[])),
                (
                    "onboarding_mode",
                    models.CharField(
                        choices=[("instant", "Instant"), ("background", "Background")],
                        default="background",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TemporaryDependentImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("main_member_identification_number", models.CharField(max_length=255)),
                ("use_type", models.CharField(max_length=255)),
                ("dependent_type", models.CharField(max_length=255)),
                (
                    "cover_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("identification_method", models.IntegerField()),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=255, null=True)),
                ("product", models.IntegerField()),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TemporaryMemberData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("username", models.EmailField(max_length=254, null=True)),
                ("firstname", models.CharField(max_length=255, null=True)),
                ("lastname", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("identification_method", models.IntegerField(null=True)),
                ("identification_number", models.CharField(max_length=255, null=True)),
                ("mobile_number", models.CharField(max_length=255, null=True)),
                ("landline", models.CharField(max_length=255, null=True)),
                ("physical_address", models.CharField(max_length=500, null=True)),
                ("postal_address", models.CharField(max_length=500, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=255, null=True)),
                ("product", models.IntegerField(null=True)),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TemporaryPaidMemberData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("identification_number", models.CharField(max_length=255)),
                ("identification_method", models.IntegerField()),
                ("product", models.IntegerField()),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
