# Generated by Django 4.1.1 on 2023-02-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryDataHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            (
                                "dependents_and_beneficiaries",
                                "Beneficiaries & Dependents",
                            ),
                            ("new_members", "New Members"),
                            ("paid_members", "Paid Members"),
                            ("cancelled_members", "Cancelled Members"),
                            ("lapsed_members", "Lapsed Members"),
                        ],
                        max_length=255,
                    ),
                ),
                ("upload_data", models.JSONField(default=[])),
                (
                    "onboarding_mode",
                    models.CharField(
                        choices=[("instant", "Instant"), ("background", "Background")],
                        default="background",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
