# Generated by Django 4.1.1 on 2023-02-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_temporarydataholding"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporarymemberdata",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
