# Generated by Django 4.1.1 on 2023-06-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_temporarymemberdata_premium"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temporarydependentimport",
            name="dependent_type",
        ),
        migrations.RemoveField(
            model_name="temporarydependentimport",
            name="use_type",
        ),
        migrations.AddField(
            model_name="temporarydependentimport",
            name="relationship",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="temporarydependentimport",
            name="relationship_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
