# Generated by Django 4.1.1 on 2023-02-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_temporarymemberdata_processed"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberUploadOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("identification_number", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("product", models.IntegerField()),
                ("reasons", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
