# Generated by Django 4.1.1 on 2023-06-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_remove_temporarydependentimport_dependent_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temporarycancelledmemberdata",
            name="main_member_identification_number",
        ),
        migrations.AddField(
            model_name="temporarycancelledmemberdata",
            name="action_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="temporarycancelledmemberdata",
            name="reference_reason",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
