# Generated by Django 4.1.1 on 2023-05-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0005_pricingplanschememapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedUploadData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("member", models.JSONField(default=dict)),
                ("member_type", models.CharField(max_length=255)),
                ("reason", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
