# Generated by Django 4.1.1 on 2023-06-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0006_alter_temporarydataholding_upload_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporarypaidmemberdata",
            name="identification_method",
            field=models.IntegerField(null=True),
        ),
    ]
