# Generated by Django 4.1.1 on 2023-06-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0006_faileduploaddata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporarymemberdata",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="temporarymemberdata",
            name="firstname",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="temporarymemberdata",
            name="identification_method",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="temporarymemberdata",
            name="identification_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="temporarymemberdata",
            name="landline",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="temporarymemberdata",
            name="lastname",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="temporarymemberdata",
            name="mobile_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="temporarymemberdata",
            name="physical_address",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="temporarymemberdata",
            name="postal_address",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="temporarymemberdata",
            name="product",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="temporarymemberdata",
            name="username",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
