# Generated by Django 4.1.1 on 2023-06-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0007_alter_temporarypaidmemberdata_identification_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporarydependentimport",
            name="identification_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
