# Generated by Django 4.1.1 on 2023-06-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("passport_number", models.CharField(max_length=255, null=True)),
                ("id_number", models.CharField(max_length=255, null=True)),
                ("address", models.TextField(null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_of_birth", models.DateField(null=True)),
                (
                    "guardian_or_trustee_first_name",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "guardian_or_trustee_last_name",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "guardian_or_trustee_phone_number",
                    models.CharField(max_length=255, null=True),
                ),
                ("guardian_or_trustee_date_of_birth", models.DateField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dependent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_additional_family_member", models.BooleanField(default=False)),
                (
                    "dependent_type",
                    models.CharField(
                        choices=[
                            ("main_member", "Main Member"),
                            ("spouse", "Spouse"),
                            ("child", "Child"),
                            ("parent", "Parent"),
                            ("extended", "Additional/Extended Family Member"),
                            ("stillborn", "Stillborn"),
                        ],
                        max_length=200,
                    ),
                ),
                ("dependent_type_notes", models.TextField(blank=True, null=True)),
                (
                    "cover_level",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("age_min", models.PositiveSmallIntegerField(null=True)),
                ("age_max", models.PositiveSmallIntegerField(null=True)),
                (
                    "age_metric",
                    models.CharField(
                        choices=[
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        max_length=100,
                    ),
                ),
                ("relative_option", models.CharField(max_length=200, null=True)),
                ("first_name", models.CharField(max_length=200, null=True)),
                ("last_name", models.CharField(max_length=200, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("female", "Female"), ("male", "Male")],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("guid", models.CharField(max_length=200, null=True)),
                ("id_number", models.CharField(max_length=255, null=True)),
                ("passport_number", models.CharField(max_length=255, null=True)),
                (
                    "add_on_premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FamilyMemberPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "pricing_group",
                    models.CharField(
                        choices=[
                            ("credit", "Credit Life"),
                            ("funeral", "Funeral"),
                            ("group", "Group"),
                            ("retail", "Retail"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "member_type",
                    models.CharField(
                        choices=[("dependent", "Dependent"), ("extended", "Extended")],
                        max_length=255,
                    ),
                ),
                (
                    "relative_type",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("child", "Child"),
                            ("extended", "Extended"),
                            ("stillborn", "Stillborn"),
                        ],
                        max_length=255,
                    ),
                ),
                ("min_age", models.IntegerField(default=0)),
                ("max_age", models.IntegerField(default=0)),
                (
                    "cover_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
