# Generated by Django 4.1.1 on 2023-06-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schemes", "0001_initial"),
        ("dependents", "0001_initial"),
        ("users", "0001_initial"),
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependent",
            name="membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.membership",
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="membership_configuration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.membershipconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="policies.policy",
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="relative",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.policyholderrelative",
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="schemegroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schemes.schemegroup",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.membership",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="policies.policy",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="relative",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.policyholderrelative",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="schemegroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schemes.schemegroup",
            ),
        ),
    ]
