# Generated by Django 4.1.1 on 2023-01-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
        ('policies', '0001_initial'),
        ('users', '0003_policyholderrelative'),
        ('dependents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuneralBeneficiary',
            new_name='Beneficiary',
        ),
    ]
