# Generated by Django 4.1.6 on 2023-08-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dependents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="relationship",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
