# Generated by Django 4.1.1 on 2023-01-29 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_policyholderrelative'),
        ('dependents', '0002_rename_funeralbeneficiary_beneficiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_additional_family_member', models.BooleanField(default=False)),
                ('dependent_type', models.CharField(choices=[('main_member', 'Main Member'), ('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('extended', 'Additional/Extended Family Member'), ('stillborn', 'Stillborn')], max_length=200)),
                ('dependent_type_notes', models.TextField(blank=True, null=True)),
                ('cover_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('age_min', models.PositiveSmallIntegerField(null=True)),
                ('age_max', models.PositiveSmallIntegerField(null=True)),
                ('age_metric', models.CharField(choices=[('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=100)),
                ('relative_option', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=200, null=True)),
                ('date_of_birth', models.DateField()),
                ('guid', models.CharField(max_length=200, null=True)),
                ('id_number', models.CharField(max_length=255, null=True)),
                ('passport_number', models.CharField(max_length=255, null=True)),
                ('add_on_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.membership')),
                ('relative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.policyholderrelative')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
