# Generated by Django 4.1.1 on 2023-04-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dependents", "0004_dependent_policy_dependent_schemegroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyMemberPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "pricing_group",
                    models.CharField(
                        choices=[
                            ("credit", "Credit Life"),
                            ("funeral", "Funeral"),
                            ("group", "Group"),
                            ("retail", "Retail"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "member_type",
                    models.CharField(
                        choices=[("dependent", "Dependent"), ("extended", "Extended")],
                        max_length=255,
                    ),
                ),
                (
                    "relative_type",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("child", "Child"),
                            ("extended", "Extended"),
                            ("stillborn", "Stillborn"),
                        ],
                        max_length=255,
                    ),
                ),
                ("min_age", models.IntegerField(default=0)),
                ("max_age", models.IntegerField(default=0)),
                (
                    "cover_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
