# Generated by Django 4.1.6 on 2023-08-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dependents", "0004_beneficiary_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependent",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
