# Generated by Django 4.1.1 on 2023-06-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_membership_policy"),
        ("dependents", "0005_familymemberpricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependent",
            name="membership_configuration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.membershipconfiguration",
            ),
        ),
    ]
