# Generated by Django 4.2.4 on 2023-09-01 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dependents", "0007_alter_dependent_relative"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dependent",
            name="relative",
        ),
    ]
