# Generated by Django 4.2.4 on 2023-09-26 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_membership_user_alter_policyholder_gender_and_more"),
        ("dependents", "0009_dependent_relative"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiary",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beneficiaries",
                to="users.membership",
            ),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependents",
                to="users.membership",
            ),
        ),
    ]
