# Generated by Django 4.2.4 on 2023-09-26 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0007_alter_policystatusupdates_policy"),
        ("dependents", "0010_alter_beneficiary_membership_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiary",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policybeneficiaries",
                to="policies.policy",
            ),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policydependents",
                to="policies.policy",
            ),
        ),
    ]
