# Generated by Django 4.1.1 on 2023-06-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("prices", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingplancovermapping",
            name="relationship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="users.policyholderrelative",
            ),
        ),
    ]
