# Generated by Django 4.1.1 on 2023-05-16 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_membership_status_remove_policyholder_country_and_more"),
        ("prices", "0002_remove_pricingplan_group_alter_pricingplan_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingplan",
            name="conditions",
        ),
        migrations.RemoveField(
            model_name="pricingplan",
            name="matrix",
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("retail", "Retail"),
                    ("group", "Group"),
                    ("credit", "Credit"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="base_premium",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="total_premium",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="value_added_service",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name="PricingPlanCoverMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("cover_level", models.DecimalField(decimal_places=2, max_digits=10)),
                ("min_age", models.IntegerField(default=0)),
                ("max_age", models.IntegerField(default=0)),
                (
                    "add_on_premium",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pricing_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prices.pricingplan",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.policyholderrelative",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
