# Generated by Django 4.1.1 on 2023-05-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0003_remove_pricingplan_conditions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingplancovermapping",
            name="cover_level",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
