# Generated by Django 4.1.6 on 2023-07-02 00:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0003_obligation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="obligation",
            old_name="included",
            new_name="is_included",
        ),
    ]
