# Generated by Django 4.1.1 on 2023-05-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0004_alter_pricingplancovermapping_cover_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlanDependentCoverPremiumMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("pricing_type", models.CharField(max_length=255)),
                ("dependent_category", models.CharField(max_length=255)),
                ("dependent_type", models.CharField(max_length=255)),
                ("min_age", models.IntegerField(default=0)),
                ("max_age", models.IntegerField(default=0)),
                ("cover_level", models.DecimalField(decimal_places=2, max_digits=10)),
                ("premium", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PricingPlanExtendedPremiumMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("pricing_plan", models.CharField(max_length=255)),
                ("min_age", models.IntegerField(default=0)),
                ("max_age", models.IntegerField(default=0)),
                ("cover_level", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "extended_premium",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
