# Generated by Django 4.1.6 on 2023-07-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0004_rename_included_obligation_is_included"),
    ]

    operations = [
        migrations.AddField(
            model_name="obligation",
            name="credit_reference",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
