# Generated by Django 4.1.1 on 2023-07-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0005_obligation_credit_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingplan",
            name="cover_levels",
            field=models.JSONField(default=list),
        ),
    ]
