# Generated by Django 4.1.1 on 2023-05-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0005_pricingplandependentcoverpremiummapping_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlanSchemeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("scheme_type", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
