# Generated by Django 4.1.1 on 2023-07-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0006_pricingplan_cover_levels"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricingplan",
            old_name="cover_levels",
            new_name="dependent_cover_levels",
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="extended_family_cover_levels",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="policy_holder_cover_levels",
            field=models.JSONField(default=list),
        ),
    ]
