# Generated by Django 4.2.4 on 2023-08-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "prices",
            "0007_rename_cover_levels_pricingplan_dependent_cover_levels_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlanCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
