# Generated by Django 4.2.4 on 2023-08-26 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0008_pricingplancategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingplan",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prices.pricingplancategory",
            ),
        ),
    ]
