# Generated by Django 4.2.4 on 2023-08-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0009_pricingplan_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingplancategory",
            name="kind",
            field=models.CharField(
                choices=[("short_term", "Short Term"), ("long_term", "Long Term")],
                default="long_term",
                max_length=255,
            ),
        ),
    ]
