# Generated by Django 4.2.4 on 2023-09-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0010_pricingplancategory_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingplan",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("retail", "Retail"),
                    ("group", "Group"),
                    ("credit", "Credit"),
                    ("funeral", "funeral"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
