# Generated by Django 4.2.4 on 2023-09-13 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0011_alter_pricingplan_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalCover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("inpatient_cover_amounts", models.JSONField(default=list)),
                ("outpatient_cover_amounts", models.JSONField(default=list)),
                (
                    "pricing_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prices.pricingplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalCoverPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "inpatient_cover",
                    models.DecimalField(decimal_places=2, max_digits=30),
                ),
                (
                    "outpatient_cover",
                    models.DecimalField(decimal_places=2, max_digits=30),
                ),
                ("ph_age_group", models.CharField(max_length=255)),
                ("ph_premium", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "spouse_premium",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("child_premium", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "medical_cover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prices.medicalcover",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
