# Generated by Django 4.2.4 on 2023-09-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0012_medicalcover_medicalcoverpricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalcoverpricing",
            name="spouse_age_group",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
