# Generated by Django 4.2.4 on 2023-09-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0013_medicalcoverpricing_spouse_age_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalcoverpricing",
            name="inpatient_premium",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="medicalcoverpricing",
            name="outpatient_premium",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="medicalcoverpricing",
            name="child_premium",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="medicalcoverpricing",
            name="ph_age_group",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="medicalcoverpricing",
            name="ph_premium",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="medicalcoverpricing",
            name="spouse_premium",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
