# Generated by Django 4.2.4 on 2023-09-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0014_medicalcoverpricing_inpatient_premium_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalcover",
            name="age_limit_description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="medicalcover",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="medicalcover",
            name="inpatient_cover_limits",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="medicalcover",
            name="outpatient_cover_limits",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="medicalcover",
            name="providers",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("retail", "Retail"),
                    ("group", "Group"),
                    ("credit", "Credit"),
                    ("pet", "Pet"),
                    ("funeral", "funeral"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
