# Generated by Django 4.2.4 on 2023-09-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet_insure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=255
            ),
        ),
    ]
