apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-insure-backend
spec:
  selector:
    matchLabels:
      app: smart-insure-backend
  template:
    metadata:
      labels:
        app: smart-insure-backend
    spec:
      containers:
      - name: smart-insure-backend
        image: 40781998/smart-insure-backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
