apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-insure-backend
spec:
  selector:
    matchLabels:
      app: smart-insure-backend
  template:
    metadata:
      labels:
        app: smart-insure-backend
    spec:
      containers:
      - name: smart-insure-backend
        image: 40781998/smart-insure-backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 8000
        env:
          - name: DB_HOST
            value: postgres
          - name: POSTGRES_DB
            value: smartsure
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: "1234"
