# Generated by Django 4.1.1 on 2023-07-28 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brokerage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("website", models.CharField(max_length=255, null=True)),
                ("phone_number", models.CharField(max_length=255, null=True)),
                (
                    "broker_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("entity", "Entity"),
                            ("internal", "Internal"),
                        ],
                        max_length=255,
                    ),
                ),
                ("contact_person", models.JSONField(null=True)),
                ("postal_address", models.CharField(max_length=255, null=True)),
                ("physical_address", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="salesagent",
            name="broker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="entities.brokerage",
            ),
        ),
        migrations.DeleteModel(
            name="Broker",
        ),
    ]
