# Generated by Django 4.1.6 on 2023-07-03 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_membership_membership_premium"),
        ("payments", "0014_alter_bankstatement_statement_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policypremium",
            name="membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membershipprems",
                to="users.membership",
            ),
        ),
    ]
