# Generated by Django 4.1.6 on 2023-07-04 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_membership_membership_premium"),
        ("payments", "0015_alter_policypremium_membership"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuturePremiumTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "expected_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("expected_date", models.DateField()),
                ("processed", models.BooleanField(default=False)),
                (
                    "membership",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.membership",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
