# Generated by Django 4.1.6 on 2023-07-04 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0004_remove_policy_broker_alter_policy_broker_information"),
        ("payments", "0016_futurepremiumtracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="futurepremiumtracking",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="policies.policy",
            ),
        ),
        migrations.AlterField(
            model_name="bankstatement",
            name="statement_type",
            field=models.CharField(
                choices=[("bank_statement", "Bank Statement"), ("receipt", "Receipt")],
                default="bank_statement",
                max_length=255,
            ),
        ),
    ]
