# Generated by Django 4.1.6 on 2023-07-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0017_futurepremiumtracking_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="futurepremiumtracking",
            name="future_expected_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="bankstatement",
            name="statement_type",
            field=models.CharField(
                choices=[("receipt", "Receipt"), ("bank_statement", "Bank Statement")],
                default="bank_statement",
                max_length=255,
            ),
        ),
    ]
