# Generated by Django 4.1.1 on 2023-07-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0018_futurepremiumtracking_future_expected_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankstatement",
            name="statement_type",
            field=models.CharField(
                choices=[("bank_statement", "Bank Statement"), ("receipt", "Receipt")],
                default="bank_statement",
                max_length=255,
            ),
        ),
    ]
