# Generated by Django 4.1.1 on 2023-07-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0019_alter_bankstatement_statement_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectedPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="bankstatement",
            name="statement_type",
            field=models.CharField(
                choices=[("receipt", "Receipt"), ("bank_statement", "Bank Statement")],
                default="bank_statement",
                max_length=255,
            ),
        ),
    ]
