# Generated by Django 4.1.6 on 2023-08-23 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0006_policy_cover_amount"),
        ("payments", "0024_alter_bankstatement_statement_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankstatement",
            name="statement_type",
            field=models.CharField(
                choices=[("bank_statement", "Bank Statement"), ("receipt", "Receipt")],
                default="bank_statement",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="policypremium",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policypremiums",
                to="policies.policy",
            ),
        ),
    ]
