# Generated by Django 4.1.7 on 2023-08-23 11:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_alter_bankstatement_statement_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policypayment',
            name='bank_statement',
        ),
        migrations.RemoveField(
            model_name='policypayment',
            name='extra_premium',
        ),
        migrations.RemoveField(
            model_name='policypayment',
            name='payment_due_date',
        ),
        migrations.RemoveField(
            model_name='policypayment',
            name='payment_path',
        ),
        migrations.RemoveField(
            model_name='policypayment',
            name='premium_reference',
        ),
        migrations.RemoveField(
            model_name='policypayment',
            name='proof_of_payment',
        ),
        migrations.RemoveField(
            model_name='policypayment',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='policypayment',
            name='vat',
        ),
        migrations.AddField(
            model_name='policypayment',
            name='amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='policypayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('debit_order', 'Debit Order'), ('stop_order', 'Stop Order'), ('off_platform', 'Off Platform'), ('mpesa', 'Mpesa')], default='Debit Order', max_length=32),
        ),
        migrations.AlterField(
            model_name='policypayment',
            name='premium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.policypremium'),
        ),
    ]
