# Generated by Django 4.1.7 on 2023-08-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_remove_policypayment_bank_statement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policypremium',
            name='payments',
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='statement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('bank_statement', 'Bank Statement')], default='bank_statement', max_length=255),
        ),
        migrations.DeleteModel(
            name='PolicyPayment',
        ),
    ]
