# Generated by Django 4.1.7 on 2023-08-23 12:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_sub_role_alter_user_role'),
        ('policies', '0006_policy_cover_amount'),
        ('payments', '0027_remove_policypremium_payments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='statement_type',
            field=models.CharField(choices=[('bank_statement', 'Bank Statement'), ('receipt', 'Receipt')], default='bank_statement', max_length=255),
        ),
        migrations.CreateModel(
            name='PolicyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('state', models.CharField(default='NEW', max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('debit_order', 'Debit Order'), ('stop_order', 'Stop Order'), ('off_platform', 'Off Platform'), ('mpesa', 'Mpesa')], default='Debit Order', max_length=32)),
                ('payment_date', models.DateField(null=True)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.membership')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.policy')),
                ('premium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.policypremium')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
