# Generated by Django 4.1.7 on 2023-08-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0028_alter_bankstatement_statement_type_policypayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankstatement',
            old_name='description',
            new_name='statement',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='statement_type',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policypayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('debit_order', 'Debit Order'), ('stop_order', 'Stop Order'), ('off_platform', 'Off Platform'), ('mpesa', 'Mpesa'), ('manual', 'Manual')], max_length=32),
        ),
    ]
