# Generated by Django 4.1.7 on 2023-08-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_rename_description_bankstatement_statement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='policy_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
