# Generated by Django 4.2.4 on 2023-08-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0030_bankstatement_policy_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="policypremium",
            name="amount_paid",
            field=models.FloatField(default=0),
        ),
    ]
