# Generated by Django 4.2.4 on 2023-08-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0031_policypremium_amount_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policypremium",
            name="reference",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
