# Generated by Django 4.2.4 on 2023-08-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0033_futurepremiumtracking_premium_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="futurepremiumtracking",
            name="new_reference",
            field=models.IntegerField(null=True),
        ),
    ]
