# Generated by Django 4.2.4 on 2023-09-19 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_role"),
        ("policies", "0006_policy_cover_amount"),
        ("payments", "0035_mpesaresponsedata_mpesatransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="policypayment",
            name="overpayment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="policypayment",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="policypremium",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "UnPaid"),
                    ("paid", "Paid"),
                    ("partial", "Partial"),
                    ("future", "Future"),
                    ("pending", "Pending"),
                    ("overpayment", "Over Payment"),
                ],
                default="future",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("payment_date", models.DateField()),
                ("processed", models.BooleanField(default=False)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.membership",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
