# Generated by Django 4.2.4 on 2023-09-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0037_paymentlog_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentlog",
            name="id_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
