# Generated by Django 4.2.4 on 2023-09-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payments",
            "0039_alter_paymentlog_amount_alter_paymentlog_membership_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentlog",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
