# Generated by Django 4.2.4 on 2023-09-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0007_alter_policystatusupdates_policy"),
        ("payments", "0043_alter_policypayment_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentlog",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="policypaymentlogs",
                to="policies.policy",
            ),
        ),
    ]
