# Generated by Django 4.2.4 on 2023-09-29 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_membership_user_alter_policyholder_gender_and_more"),
        ("payments", "0044_alter_paymentlog_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesatransaction",
            name="membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membershipmpesapayments",
                to="users.membership",
            ),
        ),
    ]
