# Generated by Django 4.2.4 on 2023-09-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0045_mpesatransaction_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesatransaction",
            name="payer_id_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
