# Generated by Django 4.1.6 on 2023-06-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipconfiguration",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membershipconfigs",
                to="users.membership",
            ),
        ),
    ]
