# Generated by Django 4.1.6 on 2023-02-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_policyholderrelative"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("None", "Without role"),
                    ("admin", "C2S Admin"),
                    ("insurer", "Insurer"),
                    ("corporate", "Corporate"),
                    ("merchant", "Merchant"),
                    ("individual", "Individual"),
                    ("report_user", "Report User"),
                    ("technician_user", "Technician User"),
                    ("foh_user", "FOH User"),
                    ("customer_support_user", "Customer Support User"),
                    ("funeral_validator", "Funeral Validator"),
                    ("brokerage_admin", "Brokerage Admin"),
                    ("broker", "Broker"),
                    ("claim_validator", "Claim Validator"),
                    ("retail_agent", "Retail Agent"),
                ],
                default="individual",
                max_length=32,
            ),
        ),
    ]
