# Generated by Django 4.1.1 on 2023-07-25 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_rename_address1_policyholder_physical_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policyholder",
            name="individual_user",
        ),
        migrations.AddField(
            model_name="policyholder",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policyholders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="IndividualUser",
        ),
    ]
