# Generated by Django 4.1.1 on 2023-02-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dependents", "0003_dependent"),
        ("prices", "0002_remove_pricingplan_group_alter_pricingplan_name"),
        ("users", "0006_individualuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "cover_level",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dependents.beneficiary",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.membership",
                    ),
                ),
                (
                    "pricing_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prices.pricingplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
