# Generated by Django 4.1.1 on 2023-02-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_membershipconfiguration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policyholder",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
