# Generated by Django 4.1.1 on 2023-07-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_policyholder_individual_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="sub_role",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("None", "Without role"),
                    ("admin", "C2S Admin"),
                    ("insurer", "Insurer"),
                    ("corporate", "Corporate"),
                    ("merchant", "Merchant"),
                    ("individual", "Individual"),
                    ("report_user", "Report User"),
                    ("technician_user", "Technician User"),
                    ("foh_user", "FOH User"),
                    ("customer_support_user", "Customer Support User"),
                    ("funeral_validator", "Funeral Validator"),
                    ("brokerage_admin", "Brokerage Admin"),
                    ("broker", "Broker"),
                    ("sales_agent", "Sales Agent"),
                    ("claim_validator", "Claim Validator"),
                    ("retail_agent", "Retail Agent"),
                ],
                max_length=32,
            ),
        ),
    ]
