# Generated by Django 4.1.1 on 2023-05-15 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0012_policy_product"),
        ("users", "0008_alter_policyholder_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="status",
        ),
        migrations.RemoveField(
            model_name="policyholder",
            name="country",
        ),
        migrations.RemoveField(
            model_name="policyholder",
            name="marital_status",
        ),
        migrations.RemoveField(
            model_name="policyholder",
            name="physical_address",
        ),
        migrations.RemoveField(
            model_name="policyholder",
            name="postal_address",
        ),
        migrations.RemoveField(
            model_name="policyholder",
            name="town",
        ),
        migrations.RemoveField(
            model_name="policyholder",
            name="user",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="home_phone_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="physical_address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="postal_address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="work_phone_number",
        ),
        migrations.AddField(
            model_name="membership",
            name="membership_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="membership_certificates"
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="membership_certificate_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membership",
            name="membership_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("created", "Created"),
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="membership_welcome_letter",
            field=models.FileField(
                blank=True, null=True, upload_to="membership_welcome_letters/"
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="properties",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="policyholder",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="policyholder",
            name="address1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="policyholder",
            name="identification_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="policyholder",
            name="individual_user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.individualuser",
            ),
        ),
        migrations.AddField(
            model_name="policyholder",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="policyholder",
            name="nationality",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="policyholder",
            name="occupation",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="policyholder",
            name="passport_number",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="policyholder",
            name="phone",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="policyholder",
            name="phone1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="policyholder",
            name="registration_number",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="address1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="identification_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="registration_number",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="policy",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="policies.policy",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="policyholder",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="policyholder",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                max_length=60,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="policyholder",
            name="id_number",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                max_length=60,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nationality",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="occupation",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
