# Generated by Django 4.1.1 on 2023-06-14 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0017_policystatusupdates"),
        ("users", "0009_remove_membership_status_remove_policyholder_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="policies.policy",
            ),
        ),
    ]
