# Generated by Django 4.1.1 on 2023-06-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("prices", "0001_initial"),
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "scheme_type",
                    models.CharField(
                        choices=[
                            ("retail", "Retail"),
                            ("group", "Group"),
                            ("credit", "Credit"),
                        ],
                        max_length=255,
                    ),
                ),
                ("max_amount_of_members", models.IntegerField(default=1)),
                ("description", models.TextField(blank=True, null=True)),
                ("master_policy", models.BooleanField(default=False)),
                ("is_group_scheme", models.BooleanField(default=False)),
                ("config", models.JSONField(null=True)),
                (
                    "policy_number_starting_counter",
                    models.PositiveIntegerField(default=1),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SchemeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("debit_order", "Debit Order"),
                            ("stop_order", "Stop Order"),
                            ("manual", "Manual"),
                            ("off_platform", "Off Platform"),
                            ("payu", "Payu"),
                            ("paygate", "Pay Gate"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("biannual", "Biannual"),
                            ("yearly", "Yearly"),
                            ("single", "Single"),
                        ],
                        max_length=255,
                    ),
                ),
                ("period_frequency", models.IntegerField(default=1)),
                (
                    "cycle_type",
                    models.CharField(
                        choices=[("member", "Member"), ("group", "Group")],
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "policy",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policies.policy",
                    ),
                ),
                (
                    "pricing_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prices.pricingplan",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schemes.scheme"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
