# Generated by Django 4.1.1 on 2023-02-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0001_initial"),
        ("schemes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schemegroup",
            name="pricing_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="prices.pricingplan",
            ),
        ),
    ]
