# Generated by Django 4.1.6 on 2023-08-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0006_policy_cover_amount"),
        ("schemes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schemegroup",
            name="policy",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schemegroups",
                to="policies.policy",
            ),
        ),
    ]
