# Generated by Django 4.1.1 on 2023-02-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schemes", "0002_schemegroup_pricing_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="schemegroup",
            name="period_frequency",
            field=models.IntegerField(default=1),
        ),
    ]
