# Generated by Django 4.1.7 on 2023-08-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_alter_schemegroup_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemegroup',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('debit_order', 'Debit Order'), ('stop_order', 'Stop Order'), ('off_platform', 'Off Platform'), ('mpesa', 'Mpesa')], max_length=255),
        ),
    ]
