# Generated by Django 4.1.1 on 2023-05-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schemes", "0003_schemegroup_period_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schemegroup",
            name="period_type",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("biannual", "Biannual"),
                    ("yearly", "Yearly"),
                    ("single", "Single"),
                ],
                max_length=255,
            ),
        ),
    ]
