# Generated by Django 4.1.1 on 2023-05-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schemes", "0004_alter_schemegroup_period_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scheme",
            old_name="max_members_number",
            new_name="max_amount_of_members",
        ),
        migrations.AddField(
            model_name="scheme",
            name="config",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="is_group_scheme",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scheme",
            name="master_policy",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="scheme_type",
            field=models.CharField(
                choices=[
                    ("retail", "Retail"),
                    ("group", "Group"),
                    ("credit", "Credit"),
                ],
                max_length=255,
            ),
        ),
    ]
