# Generated by Django 4.2.4 on 2023-09-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schemes", "0005_alter_scheme_scheme_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme",
            name="scheme_type",
            field=models.CharField(
                choices=[
                    ("retail", "Retail"),
                    ("group", "Group"),
                    ("credit", "Credit"),
                    ("pet", "Pet"),
                    ("funeral", "funeral"),
                ],
                max_length=255,
            ),
        ),
    ]
