# Generated by Django 4.1.1 on 2023-06-15 12:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=32)),
                ("sub_status", models.CharField(max_length=32, null=True)),
                ("reason", models.TextField()),
                ("sub_reason", models.CharField(max_length=255, null=True)),
                ("reference_number", models.CharField(max_length=32, unique=True)),
                ("incident_date", models.DateField()),
                ("incident_details", models.TextField(blank=True)),
                (
                    "amount",
                    models.FloatField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=0)
                        ],
                    ),
                ),
                (
                    "excess",
                    models.FloatField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=0)
                        ],
                    ),
                ),
                (
                    "maximum_indemnity",
                    models.FloatField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=0)
                        ],
                    ),
                ),
                (
                    "policy_status_when_lodged",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "proof_of_payment",
                    models.FileField(null=True, upload_to="proof_of_payments/"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClaimStatusUpdates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("previous_status", models.CharField(max_length=255)),
                ("next_status", models.CharField(max_length=255)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="claims.claim"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClaimDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_value",
                    models.FileField(null=True, upload_to="claim_documents/"),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="claims.claim"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClaimAdditionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("is_file", models.BooleanField(default=False)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="claim_additional_files/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="claims.claim"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
