# Generated by Django 4.1.1 on 2023-07-05 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dependents", "0002_initial"),
        ("users", "0005_membership_membership_premium"),
        ("claims", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimGenericFieldList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_file", models.BooleanField(default=False)),
                ("is_required", models.BooleanField(default=False)),
                ("is_standard", models.BooleanField(default=True)),
                ("reasons_allowed", models.JSONField(default=list)),
                ("claim_against_allowed", models.JSONField(default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="claim",
            name="dependent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dependents.dependent",
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="status",
            field=models.CharField(default="lodged", max_length=255),
        ),
        migrations.CreateModel(
            name="Claimant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("id_number", models.CharField(max_length=255, null=True)),
                ("passport_number", models.CharField(max_length=255, null=True)),
                ("phone_number", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("call", "Call")],
                        max_length=255,
                    ),
                ),
                ("physical_address", models.CharField(max_length=255, null=True)),
                ("postal_address", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(max_length=255, null=True)),
                (
                    "claim",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="claims.claim",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.policyholderrelative",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
