# Generated by Django 4.1.1 on 2023-02-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_remove_claim_token_claimstatusupdates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='state',
        ),
    ]
