# Generated by Django 4.1.1 on 2023-03-16 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_policyholder_phone_number"),
        ("claims", "0004_claimadditionalinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.membership",
            ),
        ),
    ]
