# Generated by Django 4.2.4 on 2023-09-26 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_membership_user_alter_policyholder_gender_and_more"),
        ("claims", "0005_alter_claim_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membershipclaims",
                to="users.membership",
            ),
        ),
    ]
