# Generated by Django 4.2.4 on 2023-09-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0007_alter_policystatusupdates_policy"),
        ("claims", "0006_alter_claim_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policyclaims",
                to="policies.policy",
            ),
        ),
    ]
