# Generated by Django 4.1.1 on 2023-06-15 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("policies", "0001_initial"),
        ("schemes", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="refundrequest",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.membership"
            ),
        ),
        migrations.AddField(
            model_name="policydetails",
            name="policy",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policy_details",
                to="policies.policy",
            ),
        ),
        migrations.AddField(
            model_name="policycancellation",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="policies.policy"
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="broker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broker_policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="insurance_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="policy_holder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.policyholder",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="upgraded_policy",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="policies.policy",
            ),
        ),
        migrations.AddField(
            model_name="lapsependingpolicy",
            name="actioned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lapsependingpolicy",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lapse_details",
                to="policies.policy",
            ),
        ),
        migrations.AddField(
            model_name="lapsenotification",
            name="membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.membership",
            ),
        ),
        migrations.AddField(
            model_name="cyclestatusupdates",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="policies.cycle",
            ),
        ),
        migrations.AddField(
            model_name="cycle",
            name="membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cycles",
                to="users.membership",
            ),
        ),
        migrations.AddField(
            model_name="cycle",
            name="scheme_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cycles",
                to="schemes.schemegroup",
            ),
        ),
        migrations.AddField(
            model_name="cancellationnotification",
            name="membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.membership",
            ),
        ),
        migrations.AddField(
            model_name="cancellationnotification",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="policies.policy",
            ),
        ),
    ]
