# Generated by Django 4.1.1 on 2023-06-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyStatusUpdates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("lapsed", "Lapsed"),
                            ("cancelled", "Cancelled"),
                            ("ntu", "NTU"),
                            ("created", "Expired"),
                            ("awaiting_payment", "Awaiting Payment"),
                            ("draft", "Draft"),
                            ("incative", "Inactive"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "next_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("lapsed", "Lapsed"),
                            ("cancelled", "Cancelled"),
                            ("ntu", "NTU"),
                            ("created", "Expired"),
                            ("awaiting_payment", "Awaiting Payment"),
                            ("draft", "Draft"),
                            ("incative", "Inactive"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
