# Generated by Django 4.1.1 on 2023-02-16 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0003_delete_insureditem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PoliyStatusUpdate",
            new_name="PolicyStatusUpdates",
        ),
    ]
