# Generated by Django 4.1.6 on 2023-06-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0003_policystatusupdates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="broker",
        ),
        migrations.AlterField(
            model_name="policy",
            name="broker_information",
            field=models.JSONField(null=True),
        ),
    ]
