# Generated by Django 4.1.1 on 2023-02-22 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_membershipstatusupdates"),
        ("schemes", "0002_schemegroup_pricing_group"),
        ("policies", "0004_rename_poliystatusupdate_policystatusupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("created", "Created"),
                            ("awaiting_payment", "Awaiting payment"),
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("lapsed", "Lapsed"),
                            ("ntu", "Not Taken Up"),
                            ("inactive", "Inactive"),
                        ],
                        default="draft",
                        max_length=255,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="users.membership",
                    ),
                ),
                (
                    "scheme_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="schemes.schemegroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CycleStatusUpdates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("created", "Created"),
                            ("awaiting_payment", "Awaiting payment"),
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("lapsed", "Lapsed"),
                            ("ntu", "Not Taken Up"),
                            ("inactive", "Inactive"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "next_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("created", "Created"),
                            ("awaiting_payment", "Awaiting payment"),
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("lapsed", "Lapsed"),
                            ("ntu", "Not Taken Up"),
                            ("inactive", "Inactive"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="policies.cycle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
