# Generated by Django 4.1.1 on 2023-07-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0005_policy_sold_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="cover_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
