# Generated by Django 4.1.1 on 2023-02-24 22:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        #("policies", "0004_rename_poliystatusupdate_policystatusupdate"),
        ("policies", "0005_cycle_cyclestatusupdates"),
    ]

    operations = []
