# Generated by Django 4.1.1 on 2023-02-26 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0003_delete_insureditem"),
        ("policies", "0005_cycle_cyclestatusupdates"),
    ]

    operations = []
