# Generated by Django 4.2.4 on 2023-09-26 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0006_policy_cover_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policystatusupdates",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policystatusupdates",
                to="policies.policy",
            ),
        ),
    ]
