# Generated by Django 4.1.1 on 2023-02-24 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0003_delete_insureditem"),
        ("policies", "0006_merge_20230224_2208"),
    ]

    operations = []
