# Generated by Django 4.1.1 on 2023-02-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0006_merge_20230226_0701"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoliyStatusUpdates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="PoliyStatusUpdates",
            new_name="PolicyStatusUpdates",
        ),
    ]
