# Generated by Django 4.1.1 on 2023-02-26 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0007_poliystatusupdate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoliyStatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="policystatusupdates",
            name="name",
        ),
        migrations.AddField(
            model_name="policystatusupdates",
            name="next_status",
            field=models.CharField(default="1", max_length=255),
        ),
        migrations.AddField(
            model_name="policystatusupdates",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="policies.policy",
            ),
        ),
        migrations.AddField(
            model_name="policystatusupdates",
            name="previous_status",
            field=models.CharField(default="1", max_length=255),
        ),
    ]
