# Generated by Django 4.1.1 on 2023-02-26 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0008_poliystatusupdate_remove_policystatusupdates_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policystatusupdates",
            name="policy",
        ),
        migrations.DeleteModel(
            name="PoliyStatusUpdate",
        ),
        migrations.DeleteModel(
            name="PolicyStatusUpdates",
        ),
    ]
