# Generated by Django 4.1.1 on 2023-02-26 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0009_remove_policystatusupdates_policy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyStatusUpdates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("previous_status", models.CharField(max_length=255)),
                ("next_status", models.CharField(max_length=255)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
