# Generated by Django 4.1.1 on 2023-02-26 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0010_policystatusupdates"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PolicyStatusUpdates",
            new_name="PolicyStatusUpdate",
        ),
    ]
