# Generated by Django 4.1.1 on 2023-03-18 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_product_type"),
        ("policies", "0011_rename_policystatusupdates_policystatusupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
            ),
        ),
    ]
