# Generated by Django 4.1.1 on 2023-05-15 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0014_alter_cycle_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PolicyCancellationX",
        ),
    ]
