# Generated by Django 4.1.1 on 2023-05-16 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_membership_status_remove_policyholder_country_and_more"),
        ("policies", "0015_delete_policycancellationx"),
    ]

    operations = [
        migrations.CreateModel(
            name="LapseNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("mobile_number", models.CharField(max_length=255, null=True)),
                ("notification_send", models.BooleanField(default=False)),
                ("policy_type", models.CharField(max_length=255, null=True)),
                ("policy_number", models.CharField(max_length=255, null=True)),
                ("policy_status", models.CharField(max_length=255, null=True)),
                ("product", models.CharField(max_length=255, null=True)),
                ("premium_expected_date", models.DateField(null=True)),
                ("is_fake_email", models.BooleanField(default=False)),
                (
                    "membership",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.membership",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CancellationNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("mobile_number", models.CharField(max_length=255, null=True)),
                ("notification_send", models.BooleanField(default=False)),
                ("policy_type", models.CharField(max_length=255, null=True)),
                ("product", models.CharField(max_length=255, null=True)),
                ("is_fake_email", models.BooleanField(default=False)),
                (
                    "membership",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.membership",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
