name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


  test-application:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: PULL REPOSITORY
        uses: actions/checkout@v2

      - name: Pytest 
        run: |
          python -m pip install --upgrade pip
          pytest -v -s


  build-docker-image:
    needs: build
    runs-on: ubuntu-latest # SO where jobs will execute.
    steps: # sequence tasks to do.
      - name: PULL REPOSITORY
        uses: actions/checkout@v2

      - name: USING ACTION TO BUILD AND PUST :)
        uses: NRO04/docker-build-push-action@v2
        with: #args for action, all of them are required
          name-repository: smart-insure-backend #repository name, specify what the repository will be called on dockerhub.
          tag: latest #tag for repository
          docker-username: ${{ secrets.DOCKER_USERNAME }} # docker account - username
          docker-password: ${{ secrets.DOCKER_PASSWORD }} # docker password, it should use access token